name: rocketbot
description: Rocketbot

publish_to: 'none'

version: 1.2.25+172

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  firebase_messaging: any
  firebase_core: any
  firebase_auth: any
  firebase_dynamic_links: any
  http: ^0.13.5
  auto_size_text: 3.0.0
  intl: ^0.17.0
  fl_chart: ^0.55.1
  progress_indicators: ^1.0.0
  url_launcher: ^6.1.5
  qr_flutter: ^4.0.0
  decimal: ^2.2.0
  flutter_snake_navigationbar: any
  cached_network_image: ^3.2.2
  permission_handler: ^10.0.0
  local_auth: ^2.1.2
  flutter_phoenix: ^1.1.0
  package_info: any
  path_provider: any
  google_sign_in: ^5.4.1
  sign_in_with_apple: ^4.1.0
  flutter_displaymode: ^0.4.0
  flutter_local_notifications: ^9.9.1
  flutter_udid: ^2.0.0
  sqflite: ^2.0.3+1
  jiffy: ^5.0.0
  sprintf: any
  slide_to_act: any
  mobile_scanner: ^2.0.0
  share_plus: ^4.1.0
  walletconnect_dart: ^0.0.11
  get_it: any
  get_version:
    git:
      url: https://github.com/Creky/get_version
      ref: master
  flutter_user_agent:
    git:
      url: https://github.com/M1chlCZ/flutter_user_agent.git
      ref: master
  flutter_biometrics:
    git:
      url: https://github.com/M1chlCZ/flutter_biometrics.git
      ref: main
  cupertino_icons: ^1.0.5
  rxdart: ^0.27.5
linter:
  rules:
    -use_super_parameters


dev_dependencies:
  flutter_lints: ^2.0.1
  logger: ^1.1.0
  flutter_native_splash: ^2.2.8
  flutter_test:
    sdk: flutter



flutter_launcher_name:
  name: "RocketBot"

flutter:
  uses-material-design: true

  generate: true

  assets:
    - images/
    - webpages/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 800
        - asset: fonts/Poppins-Light.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
          weight: 500
        - asset: fonts/JosefinSans-Medium.ttf
          weight: 600
        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 800

