name: rocketbot
description: Rocketbot

publish_to: 'none'

version: 1.2.55+202

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  firebase_messaging: any
  firebase_core: any
  firebase_auth: ^4.2.8
  http: ^0.13.5
  auto_size_text: 3.0.0
  intl: any
  fl_chart: ^0.60.0
  progress_indicators: ^1.0.0
  url_launcher: ^6.1.9
  qr_flutter: ^4.0.0
  decimal: ^2.3.2
  flutter_snake_navigationbar: any
  appinio_social_share: ^0.2.0
  cached_network_image: ^3.2.3
  permission_handler: ^10.2.0
  local_auth: ^2.1.3
  flutter_phoenix: ^1.1.0
  package_info_plus: ^3.0.3
  path_provider: any
  google_sign_in: ^6.0.0
  sign_in_with_apple: ^4.3.0
  flutter_displaymode: ^0.5.0
  flutter_local_notifications: ^13.0.0
  flutter_udid: ^2.0.1
  sqflite: ^2.2.4+1
  jiffy:
    git:
      url: https://github.com/nguyenxdat/jiffy.git
      ref: master
  sprintf: any
  slide_to_act: any
  mobile_scanner: ^2.1.0
  share_plus: ^6.3.1
  walletconnect_dart: ^0.0.11
  device_info_plus: any
  flutter_app_badger: ^1.5.0
  universal_io: any
  webviewx: ^0.2.1
  flutter_riverpod: ^2.2.0
  flutter_speed_dial: ^6.2.0
  animated_toggle_switch: ^0.6.1
  sliding_number: ^0.0.4
  animated_text_kit: ^4.2.2
  get_it: any
  flutter_user_agent:
    git:
      url: https://github.com/M1chlCZ/flutter_user_agent.git
      ref: master
  flutter_biometrics:
    git:
      url: https://github.com/M1chlCZ/flutter_biometrics.git
      ref: main
  cupertino_icons: ^1.0.5
  rxdart: ^0.27.7
  logger: any
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

linter:
  rules:
    -use_super_parameters


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter



flutter_launcher_name:
  name: "RocketBot"

flutter:
  uses-material-design: true

  generate: true

  assets:
    - images/
    - webpages/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 800
        - asset: fonts/Poppins-Light.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
          weight: 500
        - asset: fonts/JosefinSans-Medium.ttf
          weight: 600
        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 800

