name: rocketbot
description: Rocketpro

publish_to: 'none'

version: 1.2.67+215

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  firebase_messaging: any
  firebase_core: any
  firebase_auth: any
  google_sign_in: ^6.1.5
  http: ^1.1.0
  auto_size_text: 3.0.0
  intl: any
  fl_chart: ^0.63.0
  progress_indicators: ^1.0.0
  url_launcher: ^6.1.14
  qr_flutter: ^4.1.0
  decimal: ^2.3.3
  flutter_snake_navigationbar: any
  appinio_social_share: ^0.2.5
  cached_network_image: ^3.2.3
  permission_handler: ^10.4.5
  local_auth: ^2.1.7
  flutter_phoenix: ^1.1.1
  package_info_plus: ^4.1.0
  path_provider: any
  sign_in_with_apple: ^5.0.0
  flutter_displaymode: ^0.6.0
  flutter_local_notifications: ^15.1.1
  flutter_udid: ^2.0.1
  sqflite: ^2.3.0
  jiffy: ^6.2.1
  sprintf: any
  slide_to_act:
    git:
      url: https://github.com/ChargePlus/flutter-slide-to-act
      ref: master
  mobile_scanner: ^3.4.1
  share_plus: ^7.1.0
  walletconnect_dart: ^0.0.11
  device_info_plus: ^9.0.3
  flutter_app_badger: ^1.5.0
  universal_io: any
  webviewx:
    git:
      url: https://github.com/eusopht2021/webviewx
      ref: main
  flutter_riverpod: ^2.4.0
  flutter_speed_dial: ^7.0.0
  animated_toggle_switch: ^0.8.0
  sliding_number: ^0.0.4
  animated_text_kit: ^4.2.2
  get_it: any
  web_socket_channel: ^2.4.0
  flutter_user_agent:
    git:
      url: https://github.com/M1chlCZ/flutter_user_agent.git
      ref: master
  flutter_biometrics:
    git:
      url: https://github.com/M1chlCZ/flutter_biometrics.git
      ref: main
  cupertino_icons: ^1.0.6
  rxdart: ^0.27.7
  logger: any
  app_links: ^3.4.3

linter:
  rules:
    -use_super_parameters


dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter



flutter_launcher_name:
  name: "RocketPro"

flutter:
  uses-material-design: true

  generate: true

  assets:
    - images/
    - webpages/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 800
        - asset: fonts/Poppins-Light.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
          weight: 500
        - asset: fonts/JosefinSans-Medium.ttf
          weight: 600
        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 800

