// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBax2G-uSrjquMJ5uQXNz-7IorW5uLZfCM',
    appId: '1:307873550141:android:1255e5c50636a28d3a3f54',
    messagingSenderId: '307873550141',
    projectId: 'rocketbot-wallet',
    storageBucket: 'rocketbot-wallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE0x6QGh9q3Agn8_bW3I_Win15yJBiGtE',
    appId: '1:307873550141:ios:4ebdeafdb4e0d0c43a3f54',
    messagingSenderId: '307873550141',
    projectId: 'rocketbot-wallet',
    storageBucket: 'rocketbot-wallet.appspot.com',
    androidClientId: '307873550141-pq7qu1kmejvunkou7mbr3if1fq8csjjp.apps.googleusercontent.com',
    iosClientId: '307873550141-fc0qml0m8k895iess2t6l10tnuaok8q4.apps.googleusercontent.com',
    iosBundleId: 'com.m1chl.rocketbot',
  );
}
